name: Enforce Commit Messages

on:
  push:
    branches:
      - main

jobs:
  enforce-commit-messages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enforce commit message conventions
        run: |  
          commits=${{join(github.event.commits.*.message, ', ') }}
          echo $commits
